[build]
    functions = "netlify/functions"

[functions]
    node_bundler = "esbuild"
    external_node_modules = ["axios", "pdf-lib"]
    included_files = ["./node_modules/pdf-lib/**"]

[functions.scheduledDeletion]
  schedule = "15 16 * * 7"

[build.environment]
NODE_VERSION = "18"